# Generated by Django 2.2.6 on 2019-10-07 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nifi', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='nifiinstance',
            name='state',
            field=models.CharField(blank=True, default=None, max_length=100, null=True),
        ),
    ]
