# Generated by Django 2.2.6 on 2019-10-07 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nifi', '0002_nifiinstance_state'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nifiinstance',
            name='state',
            field=models.CharField(default='PENDING', max_length=100),
        ),
    ]
