# Generated by Django 2.2.6 on 2019-10-07 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nifi', '0003_auto_20191007_1748'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nifiinstance',
            name='state',
            field=models.CharField(default='PENDING_CREATE', max_length=100),
        ),
    ]
