# Generated by Django 2.2.6 on 2019-10-10 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nifi', '0004_auto_20191007_1853'),
    ]

    operations = [
        migrations.CreateModel(
            name='K8sCluster',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('status', models.CharField(max_length=255)),
                ('zone', models.CharField(max_length=255)),
                ('location', models.CharField(max_length=255)),
                ('node_count', models.IntegerField()),
                ('endpoint', models.CharField(max_length=2000)),
            ],
        ),
    ]
