# Generated by Django 2.2.6 on 2019-10-10 20:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('nifi', '0005_k8scluster'),
    ]

    operations = [
        migrations.AddField(
            model_name='nifiinstance',
            name='cluster',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='nifi.K8sCluster'),
            preserve_default=False,
        ),
    ]
