# Generated by Django 2.2.6 on 2019-10-11 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nifi', '0006_nifiinstance_cluster'),
    ]

    operations = [
        migrations.AddField(
            model_name='k8scluster',
            name='object',
            field=models.CharField(max_length=10000, null=True),
        ),
    ]
