# Generated by Django 2.2.6 on 2019-10-11 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nifi', '0007_k8scluster_object'),
    ]

    operations = [
        migrations.AlterField(
            model_name='k8scluster',
            name='object',
            field=models.BinaryField(null=True),
        ),
    ]
