# Generated by Django 2.2.6 on 2019-10-17 22:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='K8sCluster',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('status', models.CharField(max_length=255)),
                ('zone', models.CharField(max_length=255)),
                ('location', models.CharField(max_length=255)),
                ('node_count', models.IntegerField()),
                ('endpoint', models.CharField(max_length=2000)),
                ('object', models.BinaryField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='NifiInstance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('state', models.CharField(default='PENDING_CREATE', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('cluster', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nifi_web.K8sCluster')),
            ],
        ),
    ]
