# Generated by Django 2.2.6 on 2019-10-22 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nifi_web', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='nifiinstance',
            name='hostname',
            field=models.CharField(default='asdf', max_length=100),
            preserve_default=False,
        ),
    ]
