# Generated by Django 2.2.6 on 2019-11-05 16:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('nifi_web', '0002_nifiinstance_hostname'),
    ]

    operations = [
        migrations.CreateModel(
            name='NifiImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('git_repo', models.CharField(max_length=1000)),
                ('branch', models.CharField(max_length=1000)),
                ('tag', models.CharField(max_length=1000)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name='nifiinstance',
            name='image',
            field=models.CharField(default='apache/nifi:latest', max_length=1000),
        ),
        migrations.CreateModel(
            name='NifiImageBuild',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.CharField(default='PENDING_BUILD', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('cluster', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nifi_web.K8sCluster')),
            ],
        ),
    ]
