# Generated by Django 2.2.6 on 2019-11-05 21:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('nifi_web', '0003_auto_20191105_1616'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='nifiimagebuild',
            name='cluster',
        ),
        migrations.AddField(
            model_name='nifiimagebuild',
            name='image',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='nifi_web.NifiImage'),
            preserve_default=False,
        ),
    ]
