# Generated by Django 2.2.6 on 2019-11-07 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nifi_web', '0004_auto_20191105_2105'),
    ]

    operations = [
        migrations.AddField(
            model_name='nifiimagebuild',
            name='docker_id',
            field=models.CharField(default='0', max_length=1000),
            preserve_default=False,
        ),
    ]
