# Generated by Django 2.2.6 on 2019-11-07 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nifi_web', '0005_nifiimagebuild_docker_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nifiimagebuild',
            name='docker_id',
            field=models.CharField(max_length=1000, null=True),
        ),
    ]
