# Generated by Django 2.2.7 on 2019-12-10 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nifi_web', '0008_nifiinstance_namespace'),
    ]

    operations = [
        migrations.AddField(
            model_name='nifiinstance',
            name='deploy_kafka',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='nifiinstance',
            name='deploy_mongo',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='nifiinstance',
            name='deploy_prometheus',
            field=models.BooleanField(default=False),
        ),
    ]
