# Generated by Django 2.2.7 on 2019-12-20 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nifi_web', '0009_auto_20191210_1809'),
    ]

    operations = [
        migrations.AddField(
            model_name='nifiinstance',
            name='deploy_jupyter',
            field=models.BooleanField(default=False),
        ),
    ]
