# Generated by Django 2.2.7 on 2020-02-07 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nifi_web', '0014_auto_20200207_2112'),
    ]

    operations = [
        migrations.RenameField(
            model_name='imagemirror',
            old_name='image',
            new_name='from_image',
        ),
        migrations.AddField(
            model_name='imagemirror',
            name='to_image',
            field=models.CharField(default='default', max_length=1000),
            preserve_default=False,
        ),
    ]
