# Generated by Django 2.2.7 on 2020-02-12 15:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('nifi_web', '0017_instancetype_container_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='InstanceTypeIngressRoutedService',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_name', models.CharField(max_length=100)),
                ('svc_port', models.IntegerField()),
                ('target_port', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('instance_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nifi_web.InstanceType')),
            ],
        ),
    ]
