# Generated by Django 2.2.7 on 2020-02-13 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nifi_web', '0018_instancetypeingressroutedservice'),
    ]

    operations = [
        migrations.AddField(
            model_name='instancetypeingressroutedservice',
            name='name',
            field=models.CharField(default='Default', max_length=1000),
            preserve_default=False,
        ),
    ]
