# Generated by Django 2.2.7 on 2020-02-13 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nifi_web', '0019_instancetypeingressroutedservice_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instancetypeport',
            name='external',
            field=models.IntegerField(null=True),
        ),
    ]
